# 1This is a basic workflow to help you get started with Actions

name: MyTestGithubActions

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    #branches: [ master ]
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_test_job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: MyStep 1
        run: echo Hello, world! From My Step 1

      - name: MyStep 2
        run: ls -la

  my_test_job2:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!


#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
